src/server/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :users, controllers: {registrations: 'registrations'}

  namespace :professor do
      root to:'professor#index'
      resources :subjects
  end

  namespace :public do
      root to:'public#index'
      resources :blocks,      only:["index","show"]
      resources :courses,     only:["index","show"]
      resources :departments, only:["index","show"]
      resources :professors,  only:["index","show"]
      resources :rooms,       only:["index","show"]
      resources :room_types,  only:["index","show"]
      resources :subjects,    only:["index","show"]
      resources :sectors,     only:["index","show"]
      resources :klasses,     only:["index","show"]
      resources :weeks,       only:["index","show"]
      resources :appointments,only:["index","new","create"]

      post 'appointments/create', controller:'appointments', action: :create
      get 'appointments/query', to:'appointments#query', as:'appointments_query'
      get 'appointments/query_sched', to:'appointments#query_sched', as:'appointments_query_sched'
      get 'appointments/query_appoint', to:'appointments#query_appoint', as:'appointments_query_appoint'

      get "reports", to: "reports#index"

      get "db",      to: "db#index"
      get "teste",   to: "db#teste"
      #get "subjects/:subject_id/:id", to: "klasses#show"
  end

  namespace :legislation do
      resources :entities,      only:["index","show"]
  end



  namespace :about do
      root to:'about#index'
	  get "license", to: "about#license"
      resources :developers,  only:["index","show"]
      resources :tasks,       only:["index","show"]
      resources :entities,    only:["index","show"]
  end

  namespace :admin do
      resources :users
      get "select", to: "actions#select"
      get "logs",   to: "actions#log"
  end

  namespace :committee do
      get "start",  to: "actions#start"
      put "upload", to: "actions#upload"
      get "status", to: "actions#status"
      get "apagatudo", to: "actions#apagatudo"
      get "reset", to: "actions#reset", as: "reset_departments"
      get "submit", to: "actions#submit"
      get "statusdept", to: "departments#status"
      get "join_all", to: "actions#join_all_same_klasses"

      put "update_klasses", to: "actions#update_klasses"

      get "teste", to: "actions#teste"

      resources :blocks
      resources :courses
      resources :departments
      get "departments/:id/delete_klasses", to: "departments#delete_klasses"

      resources :klasses
      resources :professors
      resources :rooms
      resources :room_types
      resources :seasons
      resources :sectors
      resources :schedules
      resources :subjects
  end

  namespace :secdep do
      root to:"actions#root"

      resources :assistance
      resources :blocks
      resources :rooms
      resources :subjects
      resources :schedules
      resources :klasses
      resources :professors
      resources :equivalences
      resources :courses

      get 'changeroom',       to: 'actions#changeroom'
      get 'klassprof',        to: 'actions#klassprof'
      get 'operation',        to: 'actions#operation'
      get 'open',             to: 'actions#open'
      get 'close',            to: 'actions#close'
      get 'setrequireroom',   to: 'actions#setRequireRoom'
      get 'statistics',       to: 'actions#statistics'

      put 'join',             to: 'klasses#join'
      get 'addschedule',      to: 'klasses#addSchedule'

      match 'jt_subjects',    to: 'subjects#index', via: [:get, :post]
  end

  namespace :secsector do
      resources :appointments, only:["index", "edit", "destroy"]
      resources :blocks
      resources :departments
      resources :klasses
      resources :rooms
      resources :schedules

      get '/changeroom',     to: 'actions#changeroom'
      get 'appointments/query', to:'appointments#query'
      get 'appointments/:id/appointments/query', to:'appointments#query'
      
      get 'addschedule',      to: 'klasses#addSchedule'
  end


  namespace :ensalador do
      root to: 'actions#index'
      post 'execute',   to: 'actions#execute'
      get 'data',       to: 'actions#data'
      get 'result',     to: 'actions#result', as: "result"
  end

  namespace :management do
    root to: 'welcome#index'
  end


  root to: 'welcome#show'

  get '/welcome/show', to:'welcome#show', as:'welcome_show'
  get '/welcome/query', to:'welcome#query', as:'welcome_query'

  get '/search', to: 'search#show', as: "search"


  get '/search/autocomplete/:query', to: 'search#autocomplete', as: "search_autocomplete"


  get '/class/:id', to:  'klasses#show', as: "class"
  get '/course/:id', to: 'courses#show', as: "course"
  get '/room/:id', to:   'rooms#show', as: "room"

  get '/pudim', to: redirect('http://www.pudim.com.br'), as: 'pudim'

end

src/server/app/controllers/admin/users_controller.rb
class Admin::UsersController < ManagementController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
      @users = User.all.order("LOWER(email)").page(params[:page]).per(75)
  end

  def show; end

  def new; @user = User.new; end

  def edit; end

  def create
    @user = User.new(user_params)
    respond_to do |format|
        if @user.save
            format.html { redirect_to admin_users_url, notice: 'Usuario criado com sucesso!' }
            format.json { render :show, status: :created, location: @user }
        else
            format.html { render :new }
            format.json { render json: @user.errors, status: :unprocessable_entity }
        end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_url, notice: 'Usuário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'Usuário deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user; @user = User.find(params[:id]); end

    def user_params
        params.require(:user).permit(:email, :password, :secretary, :committee, :department_id, :sector_id, :eh_admin, :eh_committee)
    end
end

src/server/app/controllers/management/appointments_controller.rb
class Management::AppointmentsController < ManagementController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all.page(params[:page])
    $usuarioLogado = current_user
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show

  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new

  end

  # GET /appointments/1/edit
  def edit

  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Apontamento criado com sucesso!' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Apontamento atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy

    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to management_appointments_url, notice: 'Apontamento deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:week_day, :time_initial, :time_final, :status, :room)
    end
end

src/server/app/controllers/management/blocks_controller.rb
class Management::BlocksController < ManagementController
  before_action :set_block, only: [:show, :edit, :update, :destroy]
  before_action :permission_secretary, only:  [:create, :edit, :update, :destroy]
  before_action :permission_sector, only: [:create, :edit, :update, :destroy]
  before_action :permission_committee, only: [:create, :destroy]

  # GET /disciplines
  # GET /disciplines.json
  def index
    $usuarioLogado = current_user
    respond_to do |format|
        format.html {
            @blocks = Block.all
        }
        format.json {
            @blocks = Block.all
            render :json => @blocks
        }
    end

    @distances = []
    for i in 0..@blocks.size-1
        line = []
        lat1 = @blocks[i].latitude
        log1 = @blocks[i].longitude
        for j in 0..@blocks.size-1
            lat2 = @blocks[j].latitude
            log2 = @blocks[j].longitude
            lat2 = (lat1 - lat2) * (lat1 - lat2)
            log2 = (log1 - log2) * (log1 - log2)
            dist = Math.sqrt(lat2+log2) * 100000.0
            if ( dist < 10000.0 )
                line.push dist.to_i
            else
                line.push "*"
            end
        end
        @distances.push line
    end
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @block = Block.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @block = Block.new(block_params)
    @block.department = Department.find( block_params[:department_id] )

    respond_to do |format|
      if @block.save
        format.html { redirect_to management_block_path(@block), notice: 'Bloco criado com sucesso.' }
        format.json { render :show, status: :created, location: @block }
      else
        format.html { render :new }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to management_block_path(@block), notice: 'Bloco atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @block }
      else
        format.html { render :edit }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @block.destroy
    respond_to do |format|
      format.html { redirect_to management_blocks_url, notice: 'Bloco deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block
      @block = Block.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_params
      params.require(:block).permit(:code,:sector_id, :latitude, :longitude)
    end
    def permission_secretary
      if (current_user.role?('secretary'))
        render :file => 'public/422.html'

      end
    end
    def permission_committee
      if (current_user.role?('committee'))
        render :file => 'public/422.html'

      end
    end
    def permission_sector
      if (current_user.role?('sector'))
        render :file => 'public/422.html'

      end
    end
end

src/server/app/controllers/management/courses_controller.rb
class Management::CoursesController < ManagementController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :permission_secretary, only:  [:create, :edit, :update, :destroy]
  before_action :permission_sector, only: [:create, :edit, :update, :destroy]
  before_action :permission_committee, only: [:create, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    $usuarioLogado = current_user
    respond_to do |format|
        format.html {
            @courses = Course.all.page(params[:page]).per(75)
        }
        format.json {
            @courses = Course.all
            render :json => @courses
        }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
      @matrix = Matrix.new
      @matrix.loadCourse @course
  end

  # GET /courses/new
  def new
    @course = Course.new
    @departments = Department.all
  end

  # GET /courses/1/edit
  def edit

  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    #department = Department.find( course_params[:department] )
    #@course.department = department

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Curso criado com sucesso!' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to management_courses_url, notice: 'Curso atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to management_courses_url, notice: 'Curso deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :code, :department_id, :block_id)
    end
    def permission_secretary
      if current_user.role?('secretary')
        render :file => 'public/422.html'
      end
    end
    def permission_committee
      if (current_user.role?('committee'))
        render :file => 'public/422.html'
      end
    end
    def permission_sector
      if (current_user.role?('sector'))
        render :file => 'public/422.html'
      end
    end
end

src/server/app/controllers/management/users_controller.rb
class Management::UsersController < ManagementController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.page(params[:page]).per(75)
    $usuarioLogado = current_user
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.eh_admin == '0'
      @user.department = Department.find( user_params[:department_id] )
    end


    respond_to do |format|
      if @user.save
        format.html { redirect_to management_users_url, notice: 'Usuário criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to management_users_url, notice: 'Usuário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to management_users_url, notice: 'Usuário deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :eh_admin, :secretary, :committee, :department_id)
    end
end

src/server/app/controllers/management_controller.rb
class ManagementController < ApplicationController
  before_action :authenticate_user!
  layout 'management'

  def set_last
    cookies[:last] = request.fullpath
  end
end

src/server/app/views/management/users/_form.html.erb
<script type="text/javascript">
	<!--
	function showMe (it, box) {
	  var vis = (box.checked) ? "block" : "none";
	  document.getElementById(it).style.display = vis;
	}
	//-->
</script>

<%= @dados %>

<%= form_for([:management, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class:"form-control" %>
  </div>
	  <% if current_user.role?('admin')%>
  <div class="field">
    <%= f.check_box :eh_admin%><%= f.label :É_administrador %>
  </div>
	<%end%>
  <div class="field">
    <%= f.check_box :secretary%><%= f.label :É_secretário %>
  </div>
	<% if current_user.role?('admin')%>
  <div class="field">
    <%= f.check_box :committee%><%= f.label :É_Comissão %>
  </div>
	<%end%>
  <div class="field">

    <%= f.collection_select :department_id, Department.all, :id, :name, {include_blank: 'Selecione o Departamento'}, {class: 'form-control'} %>
  </div>

  <div class="field">
    <%= f.label :senha %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

src/server/app/views/management/users/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [:management, @user] %> |
<%= link_to 'Voltar', management_users_path %>

src/server/app/views/management/users/index.html.erb
<%= render partial: 'shared/management/title', locals:{title:"Usuarios",span:User.all.size}%>

<table class="table table-bordered table-hover table-border">
  <thead>
    <tr>
      <th>Email</th>
      <th>Departamento</th>
      <th>Usuário</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >

    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.department.blank?) ? "---" : link_to(user.department.name, management_department_path(user.department) %></td>
        <td>
          <% if user.role?('admin') %>
              Administrador
          <%end%>
          <% if user.role?('committee') %>
              Comissão
          <%end%>
          <% if user.role?('secretary') %>
              Secretário
          <%end%>
        </td>
        <td><%= link_to 'Mostrar', [:management, user], :class => "btn btn-default" %></td>
        <% if current_user.role?('admin')%>
          <td><%= link_to 'Editar', edit_management_user_path(user), :class => "btn btn-primary" %></td>
          <td><%= link_to 'Excluir', [:management, user], method: :delete, data: { confirm: 'Você tem certeza que deseja excluir este Usuário?' }, :class => "btn btn-danger" %></td>
        <%end%>
        <% if current_user.role?('committee') && current_user.department == user.department && user.role?('secretary')%>
            <td><%= link_to 'Editar', edit_management_user_path(user), :class => "btn btn-primary" %></td>
            <td><%= link_to 'Excluir', [:management, user], method: :delete, data: { confirm: 'Você tem certeza que deseja excluir este Usuário?' }, :class => "btn btn-danger" %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

<br>
  <% if current_user.role?('admin') || current_user.role?('committee') %>
  <%= link_to 'Novo Usuário', new_management_user_path, :class => "btn btn-primary"%>
  <%end%>

src/server/app/views/management/users/new.html.erb
<h1>Novo usuário</h1>


  <%= render 'form' %>

<%= link_to 'Back', management_users_path %>

src/server/app/views/management/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>É administrador:</strong>
  <% if @user.role?('admin') %> > sim
  <%else%> não
  <%end%>
</p>

<p>
  <strong>É Secretário:</strong>
  <% if @user.role?('secretary') %> > sim
  <%else%> não
  <%end%>
</p>

<p>
  <strong>Comissão:</strong>
  <% if @user.role?('committee') %> > sim
  <%else%> não
  <%end%>
</p>

<p>
  <strong>Department:</strong>
  <%= (@user.department.blank?) ? "None" : link_to(@user.department.name, management_department_path(@user.department)) %>
</p>